from typing import Dict, List, Any

# Control catalog defining 100 automated controls across 10 families.
# Each control defines:
#   id, name, family, description, severity, frequency, expected_result

CONTROL_DEFINITIONS: List[Dict[str, Any]] = [
    # =========================================================================
    # 1. ACCOUNTING CONTROLS (10)
    # =========================================================================
    {
        "id": "CTRL-ACC-001",
        "name": "Balance Sheet Double-Entry Identity",
        "family": "ACCOUNTING",
        "description": "Verifies that total assets exactly equal total liabilities plus equity (variance = $0.00).",
        "severity": "CRITICAL",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Assets == Liabilities + Equity (Variance == 0.00)",
    },
    {
        "id": "CTRL-ACC-002",
        "name": "Balance Roll-Forward Invariance",
        "family": "ACCOUNTING",
        "description": "Validates that for all balance sheet lines, closing balance equals opening balance plus period movements.",
        "severity": "CRITICAL",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Closing Balance == Opening Balance + Movements for 100% of accounts",
    },
    {
        "id": "CTRL-ACC-003",
        "name": "Negative Asset Balance Check",
        "family": "ACCOUNTING",
        "description": "Verifies that performing customer loans and physical securities do not have negative balances.",
        "severity": "HIGH",
        "frequency": "DAILY",
        "expected_result": "Zero accounts with unexpected negative asset balances",
    },
    {
        "id": "CTRL-ACC-004",
        "name": "Customer Deposit Overdraft Boundary",
        "family": "ACCOUNTING",
        "description": "Verifies that deposit liabilities do not carry unauthorized debit balances without formal credit line linkage.",
        "severity": "MEDIUM",
        "frequency": "DAILY",
        "expected_result": "Zero unlinked debit deposit accounts",
    },
    {
        "id": "CTRL-ACC-005",
        "name": "Equity Capital Solvency Threshold",
        "family": "ACCOUNTING",
        "description": "Verifies that regulatory capital and retained earnings remain positive and meet internal solvency minimums.",
        "severity": "CRITICAL",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Common Equity Tier 1 + Tier 2 Capital > $100.0M",
    },
    {
        "id": "CTRL-ACC-006",
        "name": "Interbank Net Placements Exposure Boundary",
        "family": "ACCOUNTING",
        "description": "Monitors net interbank lending versus borrowing exposure limits across financial counterparties.",
        "severity": "MEDIUM",
        "frequency": "DAILY",
        "expected_result": "Net interbank exposure within authorized risk appetite bounds",
    },
    {
        "id": "CTRL-ACC-007",
        "name": "Accrued Interest vs Principal Reconciliation",
        "family": "ACCOUNTING",
        "description": "Reconciles interest accrual accounts against underlying contractual instrument principal.",
        "severity": "LOW",
        "frequency": "MONTHLY",
        "expected_result": "Accrued interest balances within expected yield corridor",
    },
    {
        "id": "CTRL-ACC-008",
        "name": "Off-Balance Sheet Commitment Non-Zero Check",
        "family": "ACCOUNTING",
        "description": "Validates that active corporate credit lines carry non-negative committed and undrawn amounts.",
        "severity": "HIGH",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Undrawn amount <= Committed amount for 100% of facilities",
    },
    {
        "id": "CTRL-ACC-009",
        "name": "Multi-Currency Subledger Posting Parity",
        "family": "ACCOUNTING",
        "description": "Verifies that all foreign currency transactions balance in both transactional currency and USD base.",
        "severity": "HIGH",
        "frequency": "DAILY",
        "expected_result": "FX posting delta == 0.00 across all converted accounts",
    },
    {
        "id": "CTRL-ACC-010",
        "name": "Central Bank Clearing Cash Invariance",
        "family": "ACCOUNTING",
        "description": "Validates that physical vault cash and central bank reserve balances remain positive and unencumbered.",
        "severity": "CRITICAL",
        "frequency": "DAILY",
        "expected_result": "Central bank reserve balances > statutory reserve requirement",
    },

    # =========================================================================
    # 2. DATA QUALITY CONTROLS (10)
    # =========================================================================
    {
        "id": "CTRL-DQ-001",
        "name": "Duplicate Source Record Detection",
        "family": "DATA QUALITY",
        "description": "Scans raw transaction feeds for duplicate event IDs or identical source record timestamps.",
        "severity": "HIGH",
        "frequency": "PER_INGESTION",
        "expected_result": "Zero duplicate source transaction records",
    },
    {
        "id": "CTRL-DQ-002",
        "name": "Account Master Foreign Key Integrity",
        "family": "DATA QUALITY",
        "description": "Ensures every balance-sheet entry maps to a valid account in dim_account.",
        "severity": "CRITICAL",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Zero orphan balance-sheet positions",
    },
    {
        "id": "CTRL-DQ-003",
        "name": "Customer Existence & Master Completeness",
        "family": "DATA QUALITY",
        "description": "Ensures every active account belongs to a verified customer record in dim_customer.",
        "severity": "HIGH",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "100% accounts linked to valid customer records",
    },
    {
        "id": "CTRL-DQ-004",
        "name": "ISO-4217 Currency Code Conformance",
        "family": "DATA QUALITY",
        "description": "Validates that all account and transaction currency codes match approved ISO-4217 standards.",
        "severity": "HIGH",
        "frequency": "PER_INGESTION",
        "expected_result": "All currencies in ('USD', 'EUR', 'GBP', 'SGD', 'INR')",
    },
    {
        "id": "CTRL-DQ-005",
        "name": "ISO-3166 Country Code Conformance",
        "family": "DATA QUALITY",
        "description": "Validates that counterparty nationality codes conform to ISO-3166 alpha-3 standards.",
        "severity": "MEDIUM",
        "frequency": "DAILY",
        "expected_result": "100% valid ISO country codes",
    },
    {
        "id": "CTRL-DQ-006",
        "name": "Null Balance Detection in Active Positions",
        "family": "DATA QUALITY",
        "description": "Checks that no active balance-sheet rows contain null or NaN values in financial amount fields.",
        "severity": "CRITICAL",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Zero null monetary balances",
    },
    {
        "id": "CTRL-DQ-007",
        "name": "Future-Dated Transaction Ingestion Blocker",
        "family": "DATA QUALITY",
        "description": "Flags any transaction event with a timestamp past the reporting business close cutoff.",
        "severity": "HIGH",
        "frequency": "PER_INGESTION",
        "expected_result": "Event timestamp <= Business Date cutoff for 100% of records",
    },
    {
        "id": "CTRL-DQ-008",
        "name": "Account Status Domain Validation",
        "family": "DATA QUALITY",
        "description": "Restricts account status values to the permitted domain (ACTIVE, DORMANT, CLOSED).",
        "severity": "LOW",
        "frequency": "DAILY",
        "expected_result": "Zero unrecognized account status values",
    },
    {
        "id": "CTRL-DQ-009",
        "name": "Security ISIN Format & Checksum Verification",
        "family": "DATA QUALITY",
        "description": "Validates ISIN 12-character format and check-digit algorithm for all marketable securities.",
        "severity": "HIGH",
        "frequency": "DAILY",
        "expected_result": "100% valid ISIN identifiers in security master",
    },
    {
        "id": "CTRL-DQ-010",
        "name": "Legal Entity Hierarchy Consistency",
        "family": "DATA QUALITY",
        "description": "Validates that all account booking entities roll up to the approved consolidated reporting bank entity.",
        "severity": "HIGH",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "100% accounts map to valid consolidated legal entities",
    },

    # =========================================================================
    # 3. CLASSIFICATION CONTROLS (10)
    # =========================================================================
    {
        "id": "CTRL-CLS-001",
        "name": "100% Product Regulatory Classification Coverage",
        "family": "CLASSIFICATION",
        "description": "Verifies that every active balance-sheet position is mapped to an active Basel regulatory category.",
        "severity": "CRITICAL",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Zero unclassified or fallback regulatory positions",
    },
    {
        "id": "CTRL-CLS-002",
        "name": "Retail Depositor Balance Threshold Verification",
        "family": "CLASSIFICATION",
        "description": "Ensures retail accounts exceeding the $1.5M threshold are evaluated for less stable wholesale treatment.",
        "severity": "HIGH",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Retail accounts properly segmented by aggregate exposure",
    },
    {
        "id": "CTRL-CLS-003",
        "name": "Small Business Customer Classification Eligibility",
        "family": "CLASSIFICATION",
        "description": "Validates that counterparties classified as small business satisfy regulatory turnover thresholds.",
        "severity": "MEDIUM",
        "frequency": "MONTHLY",
        "expected_result": "100% small business entities meet eligibility rules",
    },
    {
        "id": "CTRL-CLS-004",
        "name": "Operational Deposit Relationship Agreement Validity",
        "family": "CLASSIFICATION",
        "description": "Validates that corporate operational deposits are backed by formal cash management service contracts.",
        "severity": "MEDIUM",
        "frequency": "QUARTERLY",
        "expected_result": "Operational contracts current; review flag raised if expiring in <30 days",
    },
    {
        "id": "CTRL-CLS-005",
        "name": "Deposit Insurance Scheme Coverage Flag Consistency",
        "family": "CLASSIFICATION",
        "description": "Verifies that deposits marked as insured match explicit regulatory scheme limits and eligible customer types.",
        "severity": "HIGH",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Only qualifying retail and small business deposits carry is_insured=True",
    },
    {
        "id": "CTRL-CLS-006",
        "name": "Senior Wholesale vs Subordinated Debt Separation",
        "family": "CLASSIFICATION",
        "description": "Validates that Tier 2 subordinated debt is properly isolated from senior unsecured wholesale funding.",
        "severity": "HIGH",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Subordinated debt assigned to Capital Tier 1/2 category",
    },
    {
        "id": "CTRL-CLS-007",
        "name": "Mortgage Loan-to-Value Risk Weight Partition",
        "family": "CLASSIFICATION",
        "description": "Verifies that prime residential mortgages have risk weight <= 35% to receive 50% RSF factor.",
        "severity": "HIGH",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Mortgages with RW > 35% assigned to 65% RSF category",
    },
    {
        "id": "CTRL-CLS-008",
        "name": "Sovereign Bond 0% Risk Weight Verification",
        "family": "CLASSIFICATION",
        "description": "Validates that securities classified as Level 1 HQLA hold qualifying sovereign credit ratings.",
        "severity": "CRITICAL",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "100% Level 1 securities meet zero risk-weight criteria",
    },
    {
        "id": "CTRL-CLS-009",
        "name": "Level 2A Corporate Bond Minimum Rating Check",
        "family": "CLASSIFICATION",
        "description": "Verifies that corporate debt included in Level 2A HQLA holds an external credit rating of at least AA-.",
        "severity": "HIGH",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "All Level 2A bonds rated AA- or higher",
    },
    {
        "id": "CTRL-CLS-010",
        "name": "Level 2B RMBS & BBB Bond Eligibility Verification",
        "family": "CLASSIFICATION",
        "description": "Verifies that Level 2B qualifying assets meet minimum BBB- rating and liquidity standards.",
        "severity": "MEDIUM",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "100% Level 2B assets satisfy BCBS 238 criteria",
    },

    # =========================================================================
    # 4. MATURITY CONTROLS (10)
    # =========================================================================
    {
        "id": "CTRL-MAT-001",
        "name": "Residual Maturity Non-Negative Invariance",
        "family": "MATURITY",
        "description": "Validates that contractual maturity date is not prior to the reporting business date.",
        "severity": "CRITICAL",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Maturity Date >= Business Date for all active performing contracts",
    },
    {
        "id": "CTRL-MAT-002",
        "name": "Calendar Date Format & Tenor Validity",
        "family": "MATURITY",
        "description": "Validates that all maturity dates are valid calendar dates and non-corrupt.",
        "severity": "HIGH",
        "frequency": "DAILY",
        "expected_result": "Zero date parsing or formatting anomalies",
    },
    {
        "id": "CTRL-MAT-003",
        "name": "Demand Deposit Residual Bucketing Rule",
        "family": "MATURITY",
        "description": "Ensures contractual overnight demand deposits are mapped to residual bucket <6M.",
        "severity": "HIGH",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "100% demand deposits placed in <6M residual tenor bucket",
    },
    {
        "id": "CTRL-MAT-004",
        "name": "Term Deposit Contractual vs Residual Tenor Alignment",
        "family": "MATURITY",
        "description": "Verifies that residual maturity is mathematically consistent with open date and original tenor.",
        "severity": "MEDIUM",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Residual maturity <= Original contractual tenor",
    },
    {
        "id": "CTRL-MAT-005",
        "name": "Certificate of Deposit 6M-1Y Tenor Partition",
        "family": "MATURITY",
        "description": "Verifies wholesale funding with 180D to <365D tenor receives 50% ASF factor under BCBS 295.",
        "severity": "HIGH",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Wholesale CDs with residual tenor 180D-365D mapped to Rule RULE-ASF-06",
    },
    {
        "id": "CTRL-MAT-006",
        "name": "Wholesale Long-Term Debt >= 1Y Tenor Check",
        "family": "MATURITY",
        "description": "Validates that senior notes receiving 100% ASF have an effective residual maturity >= 365 days.",
        "severity": "CRITICAL",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "All 100% ASF wholesale debt has residual maturity >= 365 days",
    },
    {
        "id": "CTRL-MAT-007",
        "name": "Residential Mortgage Tenor Horizon Validity",
        "family": "MATURITY",
        "description": "Verifies that long-term amortizing mortgage books reflect valid residual amortizing schedules.",
        "severity": "MEDIUM",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Mortgage residual maturity within approved 30-year statutory boundary",
    },
    {
        "id": "CTRL-MAT-008",
        "name": "Short Financial Funding LCR 30-Day Stress Flag",
        "family": "MATURITY",
        "description": "Flags financial counterparty borrowings maturing in <= 30 days for 100% LCR cash outflow.",
        "severity": "HIGH",
        "frequency": "DAILY",
        "expected_result": "100% interbank liabilities <= 30D assigned to 100% LCR outflow",
    },
    {
        "id": "CTRL-MAT-009",
        "name": "Non-Performing Loan Past-Due Aging Check",
        "family": "MATURITY",
        "description": "Verifies that loans flagged as NPL have been past due for >= 90 days.",
        "severity": "HIGH",
        "frequency": "MONTHLY",
        "expected_result": "100% NPL exposures have days_past_due >= 90",
    },
    {
        "id": "CTRL-MAT-010",
        "name": "Perpetual Equity Maturity Invariance",
        "family": "MATURITY",
        "description": "Ensures CET1 equity and perpetual capital instruments carry perpetual tenor designation.",
        "severity": "HIGH",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Maturity bucket == 'PERPETUAL' for all equity instruments",
    },

    # =========================================================================
    # 5. CALCULATION CONTROLS (10)
    # =========================================================================
    {
        "id": "CTRL-CAL-001",
        "name": "NSFR Denominator Non-Zero Validation",
        "family": "CALCULATION",
        "description": "Verifies that Required Stable Funding (RSF) is strictly positive to prevent division by zero.",
        "severity": "CRITICAL",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "RSF > $0.00",
    },
    {
        "id": "CTRL-CAL-002",
        "name": "LCR Net Outflows Non-Zero Validation",
        "family": "CALCULATION",
        "description": "Verifies that total net cash outflows over 30 days is strictly positive.",
        "severity": "CRITICAL",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Net Cash Outflows > $0.00",
    },
    {
        "id": "CTRL-CAL-003",
        "name": "ASF Factor Boundary Constraint",
        "family": "CALCULATION",
        "description": "Ensures all applied Available Stable Funding factors lie strictly in the set {0.0, 0.50, 0.90, 0.95, 1.0}.",
        "severity": "CRITICAL",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "All applied ASF factors match authorized regulatory values",
    },
    {
        "id": "CTRL-CAL-004",
        "name": "RSF Factor Boundary Constraint",
        "family": "CALCULATION",
        "description": "Ensures all applied Required Stable Funding factors lie strictly in the set {0.0, 0.05, 0.10, 0.15, 0.50, 0.65, 0.85, 1.0}.",
        "severity": "CRITICAL",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "All applied RSF factors match authorized regulatory values",
    },
    {
        "id": "CTRL-CAL-005",
        "name": "LCR Outflow Rate Domain Check",
        "family": "CALCULATION",
        "description": "Ensures 30-day cash outflow run-off rates lie strictly between 0.0000 and 1.0000.",
        "severity": "HIGH",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "0.0 <= Outflow Rate <= 1.0 for 100% of positions",
    },
    {
        "id": "CTRL-CAL-006",
        "name": "HQLA Level 2 Asset 40% Cap Adherence",
        "family": "CALCULATION",
        "description": "Verifies that Level 2 assets do not comprise more than 40% of the total adjusted HQLA buffer.",
        "severity": "HIGH",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Level 2 HQLA <= 40% of total buffer or haircut applied",
    },
    {
        "id": "CTRL-CAL-007",
        "name": "HQLA Level 2B Asset 15% Cap Adherence",
        "family": "CALCULATION",
        "description": "Verifies that Level 2B assets do not comprise more than 15% of the total adjusted HQLA buffer.",
        "severity": "HIGH",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Level 2B HQLA <= 15% of total buffer or haircut applied",
    },
    {
        "id": "CTRL-CAL-008",
        "name": "LCR Contractual Cash Inflow 75% Ceiling",
        "family": "CALCULATION",
        "description": "Enforces statutory rule that eligible cash inflows cannot exceed 75% of total gross cash outflows.",
        "severity": "CRITICAL",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Eligible Inflows <= 0.75 * Gross Outflows",
    },
    {
        "id": "CTRL-CAL-009",
        "name": "Fixed-Point Decimal Rounding Verification",
        "family": "CALCULATION",
        "description": "Verifies that all financial aggregation operations utilize ROUND_HALF_EVEN decimal arithmetic.",
        "severity": "HIGH",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Zero floating-point IEEE-754 precision drift",
    },
    {
        "id": "CTRL-CAL-010",
        "name": "Metric Snapshot Recalculation Parity",
        "family": "CALCULATION",
        "description": "Independently recalculates NSFR from component tables and asserts zero variance against persisted metric.",
        "severity": "CRITICAL",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Recalculated NSFR == Persisted NSFR (Variance == 0.0000 pp)",
    },

    # =========================================================================
    # 6. RECONCILIATION CONTROLS (10)
    # =========================================================================
    {
        "id": "CTRL-REC-001",
        "name": "Subledger to General Ledger Summary Parity",
        "family": "RECONCILIATION",
        "description": "Reconciles granular subledger accounts to General Ledger control account summary totals.",
        "severity": "CRITICAL",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Subledger Total == General Ledger Control Total ($0.00 variance)",
    },
    {
        "id": "CTRL-REC-002",
        "name": "Central Bank Settlement Account Reconciliation",
        "family": "RECONCILIATION",
        "description": "Reconciles internal cash balances against official central bank account confirmation statements.",
        "severity": "HIGH",
        "frequency": "DAILY",
        "expected_result": "Zero unexplained cash ledger settlement variances",
    },
    {
        "id": "CTRL-REC-003",
        "name": "Depository Custody Security Holding Parity",
        "family": "RECONCILIATION",
        "description": "Reconciles internal treasury security positions against depository trust custodian confirmations.",
        "severity": "HIGH",
        "frequency": "DAILY",
        "expected_result": "Internal security quantity == Depository confirmation quantity",
    },
    {
        "id": "CTRL-REC-004",
        "name": "Loan Servicing Subledger to Balance Sheet Parity",
        "family": "RECONCILIATION",
        "description": "Reconciles loan servicing core books to balance-sheet performing principal accounts.",
        "severity": "HIGH",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Loan Servicing Total == Balance Sheet Loan Total ($0.00 variance)",
    },
    {
        "id": "CTRL-REC-005",
        "name": "Deposit Subledger to Balance Sheet Parity",
        "family": "RECONCILIATION",
        "description": "Reconciles core retail and corporate deposit systems to balance-sheet customer deposit totals.",
        "severity": "HIGH",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "Core Deposit Total == Balance Sheet Deposit Total ($0.00 variance)",
    },
    {
        "id": "CTRL-REC-006",
        "name": "Off-Balance Sheet Credit Lines to Facility Master",
        "family": "RECONCILIATION",
        "description": "Reconciles committed credit facilities on balance sheet against commercial facility contracts.",
        "severity": "HIGH",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "100% facility commitments match approved credit agreements",
    },
    {
        "id": "CTRL-REC-007",
        "name": "Interbank Counterparty Confirmation Matching",
        "family": "RECONCILIATION",
        "description": "Matches interbank borrowings against counterparty confirmation notices and broker matching feeds.",
        "severity": "MEDIUM",
        "frequency": "DAILY",
        "expected_result": "All trades confirmed; pending confirmations flagged if >24 hours",
    },
    {
        "id": "CTRL-REC-008",
        "name": "Post-Freeze Data Mutation Guard",
        "family": "RECONCILIATION",
        "description": "Verifies that source tables have received zero inserts or updates after close stage 1 data freeze.",
        "severity": "CRITICAL",
        "frequency": "CONTINUOUS",
        "expected_result": "Zero database mutations on frozen snapshot tables",
    },
    {
        "id": "CTRL-REC-009",
        "name": "Market FX Rate Feed Benchmark Reconciliation",
        "family": "RECONCILIATION",
        "description": "Reconciles internal exchange rates against official central bank mid-market closing fixings.",
        "severity": "MEDIUM",
        "frequency": "DAILY",
        "expected_result": "FX rates match official fixings within 0.05% tolerance",
    },
    {
        "id": "CTRL-REC-010",
        "name": "Manual Journal Entry Four-Eye Approval Verification",
        "family": "RECONCILIATION",
        "description": "Verifies that every manual balance-sheet adjustment carries dual controller sign-off.",
        "severity": "CRITICAL",
        "frequency": "PER_CLOSE_CYCLE",
        "expected_result": "100% manual journals have verified reviewer approval",
    },

    # =========================================================================
    # 7. REPORTING CONTROLS (10)
    # =========================================================================
    {
        "id": "CTRL-REP-001",
        "name": "Reporting Snapshot Immutability & Seal Verification",
        "family": "REPORTING",
        "description": "Verifies that published reporting packs are generated strictly from sealed, frozen snapshots.",
        "severity": "CRITICAL",
        "frequency": "PER_REPORT_GENERATION",
        "expected_result": "Snapshot status == 'FROZEN' or 'SIGNED_OFF'",
    },
    {
        "id": "CTRL-REP-002",
        "name": "Executive Summary Cell to Database Reconciliation",
        "family": "REPORTING",
        "description": "Reconciles published executive summary cells against underlying database liquidity metrics.",
        "severity": "CRITICAL",
        "frequency": "PER_REPORT_GENERATION",
        "expected_result": "Report Cell NSFR == FactLiquidityMetric.ratio_value",
    },
    {
        "id": "CTRL-REP-003",
        "name": "NSFR Reporting Table Line Summation Integrity",
        "family": "REPORTING",
        "description": "Verifies that individual rows in the published NSFR schedule sum exactly to total ASF and RSF.",
        "severity": "HIGH",
        "frequency": "PER_REPORT_GENERATION",
        "expected_result": "Sum(Row ASF) == Total ASF; Sum(Row RSF) == Total RSF",
    },
    {
        "id": "CTRL-REP-004",
        "name": "LCR Reporting Table Component Summation Integrity",
        "family": "REPORTING",
        "description": "Verifies that individual HQLA and cash outflow lines sum to published totals.",
        "severity": "HIGH",
        "frequency": "PER_REPORT_GENERATION",
        "expected_result": "Sum(HQLA Rows) == Total HQLA; Sum(Outflows) == Net Outflows",
    },
    {
        "id": "CTRL-REP-005",
        "name": "Balance-Sheet Reconciliation Table Zero Variance",
        "family": "REPORTING",
        "description": "Verifies that the published balance-sheet reconciliation schedule displays $0.00 unexplained difference.",
        "severity": "CRITICAL",
        "frequency": "PER_REPORT_GENERATION",
        "expected_result": "Reconciliation difference == $0.00",
    },
    {
        "id": "CTRL-REP-006",
        "name": "Variance Commentary Attribution Consistency",
        "family": "REPORTING",
        "description": "Verifies that movements cited in narrative commentary match mathematical Shapley driver values.",
        "severity": "HIGH",
        "frequency": "PER_REPORT_GENERATION",
        "expected_result": "Top 3 commentary drivers match mathematical attribution rank",
    },
    {
        "id": "CTRL-REP-007",
        "name": "Regulatory Rule Version Citation Integrity",
        "family": "REPORTING",
        "description": "Verifies that report header citations match the active version in regulatory_rules.",
        "severity": "MEDIUM",
        "frequency": "PER_REPORT_GENERATION",
        "expected_result": "Report Rule Version == RegulatoryRule.rule_version",
    },
    {
        "id": "CTRL-REP-008",
        "name": "Reporting Unit & Scale Standardization",
        "family": "REPORTING",
        "description": "Verifies that all monetary figures in schedules are displayed in uniform reporting units (USD Millions).",
        "severity": "LOW",
        "frequency": "PER_REPORT_GENERATION",
        "expected_result": "100% cells formatted with standard 1 decimal place ($M)",
    },
    {
        "id": "CTRL-REP-009",
        "name": "Comparative Baseline Period Availability Check",
        "family": "REPORTING",
        "description": "Ensures prior comparative period data is available and sealed before generating variance schedules.",
        "severity": "HIGH",
        "frequency": "PER_REPORT_GENERATION",
        "expected_result": "Prior period snapshot exists and is sealed",
    },
    {
        "id": "CTRL-REP-010",
        "name": "Unresolved Blocking Exception Publication Gate",
        "family": "REPORTING",
        "description": "Blocks report pack generation if any CRITICAL control exception remains unresolved or unapproved.",
        "severity": "CRITICAL",
        "frequency": "PER_REPORT_GENERATION",
        "expected_result": "Zero open CRITICAL exceptions before report publication",
    },

    # =========================================================================
    # 8. LINEAGE CONTROLS (10)
    # =========================================================================
    {
        "id": "CTRL-LIN-001",
        "name": "Lineage Graph Strict Acyclicity Verification",
        "family": "LINEAGE",
        "description": "Verifies using cycle detection algorithms that the data lineage graph contains zero circular dependencies.",
        "severity": "CRITICAL",
        "frequency": "PER_LINEAGE_BUILD",
        "expected_result": "NetworkX is_directed_acyclic_graph(G) == True",
    },
    {
        "id": "CTRL-LIN-002",
        "name": "Metric Node Provenance Link Completeness",
        "family": "LINEAGE",
        "description": "Verifies that every top-level metric node possesses incoming edges from contribution nodes.",
        "severity": "CRITICAL",
        "frequency": "PER_LINEAGE_BUILD",
        "expected_result": "In-degree(Metric) >= 2 (ASF and RSF predecessors exist)",
    },
    {
        "id": "CTRL-LIN-003",
        "name": "Contribution to Regulatory Rule Linkage Check",
        "family": "LINEAGE",
        "description": "Verifies that every calculated contribution node is connected to an active regulatory rule node.",
        "severity": "HIGH",
        "frequency": "PER_LINEAGE_BUILD",
        "expected_result": "100% of contribution nodes trace to active rule definitions",
    },
    {
        "id": "CTRL-LIN-004",
        "name": "Accounting Position to Source Event Drill-Down",
        "family": "LINEAGE",
        "description": "Verifies that all balance-sheet position nodes have backward traversal paths to supporting source events.",
        "severity": "HIGH",
        "frequency": "PER_LINEAGE_BUILD",
        "expected_result": "100% of positions possess source event predecessors",
    },
    {
        "id": "CTRL-LIN-005",
        "name": "Orphan Lineage Node Detection",
        "family": "LINEAGE",
        "description": "Detects disconnected or orphan nodes in the lineage graph with neither predecessors nor successors.",
        "severity": "MEDIUM",
        "frequency": "PER_LINEAGE_BUILD",
        "expected_result": "Zero disconnected orphan nodes in lineage graph",
    },
    {
        "id": "CTRL-LIN-006",
        "name": "Topological Sort Order Integrity",
        "family": "LINEAGE",
        "description": "Validates that calculations execute in valid topological sequence from source to reporting nodes.",
        "severity": "CRITICAL",
        "frequency": "PER_LINEAGE_BUILD",
        "expected_result": "Valid topological order exists across all graph nodes",
    },
    {
        "id": "CTRL-LIN-007",
        "name": "Edge Weight Conservation Across Aggregations",
        "family": "LINEAGE",
        "description": "Verifies that sum of incoming edge weights to an aggregation node equals the node value.",
        "severity": "HIGH",
        "frequency": "PER_LINEAGE_BUILD",
        "expected_result": "Sum(Incoming weights) == Target node aggregated balance",
    },
    {
        "id": "CTRL-LIN-008",
        "name": "Lineage Run Timestamp Consistency",
        "family": "LINEAGE",
        "description": "Verifies that the lineage execution timestamp is aligned with the active snapshot calculation run.",
        "severity": "LOW",
        "frequency": "PER_LINEAGE_BUILD",
        "expected_result": "Lineage run executed_at >= snapshot calculation timestamp",
    },
    {
        "id": "CTRL-LIN-009",
        "name": "Metric Birth Certificate End-to-End Traversal",
        "family": "LINEAGE",
        "description": "Tests full backward traversal from report cell to source transaction to ensure uninterrupted audit path.",
        "severity": "CRITICAL",
        "frequency": "PER_LINEAGE_BUILD",
        "expected_result": "Unbroken path exists from metric down to raw source events",
    },
    {
        "id": "CTRL-LIN-010",
        "name": "Blast Radius Forward Reachability Integrity",
        "family": "LINEAGE",
        "description": "Verifies that control failure blast-radius algorithm correctly propagates to downstream metric and report nodes.",
        "severity": "HIGH",
        "frequency": "PER_LINEAGE_BUILD",
        "expected_result": "Forward traversal discovers all dependent downstream entities",
    },

    # =========================================================================
    # 9. SCENARIO CONTROLS (10)
    # =========================================================================
    {
        "id": "CTRL-SCN-001",
        "name": "Scenario Stress Parameter Boundary Validation",
        "family": "SCENARIO",
        "description": "Validates that scenario shock parameters remain within realistic stress testing limits (+/- 50%).",
        "severity": "MEDIUM",
        "frequency": "PER_SCENARIO_RUN",
        "expected_result": "-0.50 <= Shock Parameter <= +0.50",
    },
    {
        "id": "CTRL-SCN-002",
        "name": "Baseline Snapshot Immutability Guard",
        "family": "SCENARIO",
        "description": "Verifies that running a counterfactual scenario does not alter a single record in the baseline snapshot.",
        "severity": "CRITICAL",
        "frequency": "PER_SCENARIO_RUN",
        "expected_result": "Base snapshot hash identical before and after scenario execution",
    },
    {
        "id": "CTRL-SCN-003",
        "name": "Scenario Double-Entry Parity Invariance",
        "family": "SCENARIO",
        "description": "Ensures projected balance sheet under stress satisfies Assets == Liabilities + Equity.",
        "severity": "CRITICAL",
        "frequency": "PER_SCENARIO_RUN",
        "expected_result": "Scenario Assets == Scenario Liabilities + Equity ($0.00 variance)",
    },
    {
        "id": "CTRL-SCN-004",
        "name": "Asset Reallocation Value Conservation",
        "family": "SCENARIO",
        "description": "Verifies that under asset reallocation stress, cash generated by sales matches cash deployed in purchases.",
        "severity": "HIGH",
        "frequency": "PER_SCENARIO_RUN",
        "expected_result": "Sold Assets Proceeds == Purchased Assets Cost ($0.00 cash leak)",
    },
    {
        "id": "CTRL-SCN-005",
        "name": "Wholesale Funding Maturity Cash Drain Conservation",
        "family": "SCENARIO",
        "description": "Verifies that maturing wholesale debt reduces liquid cash reserves dollar-for-dollar.",
        "severity": "HIGH",
        "frequency": "PER_SCENARIO_RUN",
        "expected_result": "Delta Wholesale Liabilities == Delta Cash Reserves",
    },
    {
        "id": "CTRL-SCN-006",
        "name": "Corporate Deposit Outflow Cash Buffer Depletion Check",
        "family": "SCENARIO",
        "description": "Ensures simulated deposit outflows deplete cash and central bank reserves within buffer capacity.",
        "severity": "HIGH",
        "frequency": "PER_SCENARIO_RUN",
        "expected_result": "Post-stress cash reserves remain >= 0.00",
    },
    {
        "id": "CTRL-SCN-007",
        "name": "Loan Growth Funding Source Identification",
        "family": "SCENARIO",
        "description": "Verifies that simulated loan expansion specifies a balancing funding source (cash drain or debt issue).",
        "severity": "HIGH",
        "frequency": "PER_SCENARIO_RUN",
        "expected_result": "New loans balanced by corresponding liability increase or asset reduction",
    },
    {
        "id": "CTRL-SCN-008",
        "name": "Combined Stress Compound Non-Negativity Check",
        "family": "SCENARIO",
        "description": "Ensures that combining multiple simultaneous stress shocks does not produce negative balances.",
        "severity": "MEDIUM",
        "frequency": "PER_SCENARIO_RUN",
        "expected_result": "All stressed account balances >= 0.00",
    },
    {
        "id": "CTRL-SCN-009",
        "name": "Scenario Delta Reconciled Attribution Check",
        "family": "SCENARIO",
        "description": "Verifies that delta NSFR equals scenario NSFR minus base NSFR within 0.0001 pp.",
        "severity": "CRITICAL",
        "frequency": "PER_SCENARIO_RUN",
        "expected_result": "Delta NSFR == Stressed NSFR - Base NSFR",
    },
    {
        "id": "CTRL-SCN-010",
        "name": "Scenario Sandbox Ephemeral Isolation",
        "family": "SCENARIO",
        "description": "Verifies that scenario projection runs operate in isolated memory or versioned tables without table locking.",
        "severity": "MEDIUM",
        "frequency": "PER_SCENARIO_RUN",
        "expected_result": "Zero schema locks or persistent side effects on core ledger",
    },

    # =========================================================================
    # 10. AI OUTPUT CONTROLS (10)
    # =========================================================================
    {
        "id": "CTRL-AI-001",
        "name": "AI NSFR Numeric Value Grounding Verification",
        "family": "AI OUTPUT",
        "description": "Verifies that any NSFR percentage cited in AI narrative matches the verified calculation within 0.01 pp.",
        "severity": "CRITICAL",
        "frequency": "PER_AI_QUERY",
        "expected_result": "abs(AI_NSFR - Validated_NSFR) <= 0.01",
    },
    {
        "id": "CTRL-AI-002",
        "name": "AI LCR Numeric Value Grounding Verification",
        "family": "AI OUTPUT",
        "description": "Verifies that any LCR percentage cited in AI narrative matches the verified calculation within 0.01 pp.",
        "severity": "CRITICAL",
        "frequency": "PER_AI_QUERY",
        "expected_result": "abs(AI_LCR - Validated_LCR) <= 0.01",
    },
    {
        "id": "CTRL-AI-003",
        "name": "AI Largest Driver Attribution Parity",
        "family": "AI OUTPUT",
        "description": "Verifies that the primary driver named by the AI matches the rank-1 contributor from Shapley attribution.",
        "severity": "HIGH",
        "frequency": "PER_AI_QUERY",
        "expected_result": "AI_Top_Driver == Shapley_Top_Driver",
    },
    {
        "id": "CTRL-AI-004",
        "name": "AI Reporting Period Context Conformance",
        "family": "AI OUTPUT",
        "description": "Verifies that the reporting period cited in the AI narrative matches the requested query context.",
        "severity": "HIGH",
        "frequency": "PER_AI_QUERY",
        "expected_result": "AI_Period == Query_Context_Period",
    },
    {
        "id": "CTRL-AI-005",
        "name": "AI Currency Unit & Scale Conformance",
        "family": "AI OUTPUT",
        "description": "Verifies that monetary amounts cited by the AI utilize the correct currency ($) and scale ($M).",
        "severity": "MEDIUM",
        "frequency": "PER_AI_QUERY",
        "expected_result": "Currency symbol == '$' and scale matches underlying numbers",
    },
    {
        "id": "CTRL-AI-006",
        "name": "AI Directional Claim Consistency Verification",
        "family": "AI OUTPUT",
        "description": "Verifies that directional claims (e.g. 'declined', 'rose') match the algebraic sign of the delta.",
        "severity": "CRITICAL",
        "frequency": "PER_AI_QUERY",
        "expected_result": "'decreased' asserted iff delta < 0; 'increased' asserted iff delta > 0",
    },
    {
        "id": "CTRL-AI-007",
        "name": "Hallucinated Financial Metric Blocker",
        "family": "AI OUTPUT",
        "description": "Detects and blocks any AI statement citing unregistered financial acronyms or fake regulatory metrics.",
        "severity": "CRITICAL",
        "frequency": "PER_AI_QUERY",
        "expected_result": "Zero unallowlisted metric tokens in generated response",
    },
    {
        "id": "CTRL-AI-008",
        "name": "Arbitrary SQL Keyword Injection Blocker",
        "family": "AI OUTPUT",
        "description": "Ensures that AI inputs and outputs contain zero raw executable SQL commands or injection patterns.",
        "severity": "CRITICAL",
        "frequency": "PER_AI_QUERY",
        "expected_result": "Zero SQL injection tokens detected",
    },
    {
        "id": "CTRL-AI-009",
        "name": "Contradictory Exception Count Blocker",
        "family": "AI OUTPUT",
        "description": "Verifies that exception counts stated by the AI exactly match open exceptions in fact_exception.",
        "severity": "HIGH",
        "frequency": "PER_AI_QUERY",
        "expected_result": "AI_Exception_Count == Count(fact_exception WHERE status='OPEN')",
    },
    {
        "id": "CTRL-AI-010",
        "name": "Mandatory Audit Grounding Citation Check",
        "family": "AI OUTPUT",
        "description": "Verifies that every factual claim in the AI narrative is accompanied by a structured database source reference.",
        "severity": "HIGH",
        "frequency": "PER_AI_QUERY",
        "expected_result": "100% of claims possess valid grounding source references",
    },
]
